In [1]:
%pip install -e .


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Obtaining file:///home/772a0560-9cb7-4270-b879-16761470b567/quantum_gate_package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for quantum-gate-package (pyproject.toml) ... done
  Created wheel for quantum-gate-package: filename=quantum_gate_package-0.1.0-0.editable-py3-none-any.whl size=2665 sha256=877491ee5410bb2161cc747885a90ef1eb56613e1cef09eaf860ad2f12cde1e6
  Stored in directory: /tmp/pip-ephem-wheel-cache-th2z80jd/wheels/54/d6/5f/f62616e79a744ee2b48e1e8952df3b17802a399c391d96e721
Successfully built quantum-gate-package
  Attempting uninstall: quantum-gate-package
    Found existing installation: quantum-gate-package 0.1.0
    Uninstalling quantum-gate-package-0.1.0:
      Successfully

This program builds a general control gate (Controlled-U) for an N-qubit quantum register

• Works for any number of qubits (N)
• Control and target qubits can be at any position
• Works on any quantum state (superposition / entangled)

In [6]:
from quantum_gate_package import I, X, Y, Z, H, P0, P1, controlled_gate

In [21]:
import numpy as np

#Example 1
N = 3 

# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 3-qubit CNOT (control=2, target=0)
N = 3
control = 0
target = 1

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

# Example 3: 2-qubit CNOT (control=2, target=0)
N = 2
control =1
target = 0

CNOT= controlled_gate(X, control, target, N)
print(CNOT)

N = 4
control = 0
target = 3

C_X = controlled_gate(I, control, target, N)
print(C_X)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


Create a function that generates a complete set of projectors
(computational basis)

{𝑃𝑖}, 𝑃𝑖=∣𝑖⟩⟨𝑖∣

In [ ]:
import numpy as np

def projectors(dim):
    """
    Generate computational basis projectors {|i><i|}.
    """
    projectors = []
    for i in range(dim):
        ket = np.zeros(dim)
        ket[i] = 1.0
        P = np.outer(ket, ket)
        projectors.append(P)
    return projectors

    #Example
P = projectors(2)
print(P[0])
print(P[1])

In [ ]:
import numpy as np

def projector(dim):
    """
    Generate computational basis projector {|i><i|}.
    """
    projector = []
    for i in range(dim):
        ket = np.zeros(dim)
        ket[i] = 1
        P = np.outer(ket, ket)
        projector.append(P)
    return projector

    #Example
P = projector(4)
print(P[0])
print(P[3])

Born rule function

𝑝𝑖=Tr(𝑃𝑖𝜌)

In [ ]:
import numpy as np

def born_rule(rho, projectors):
    """
    Compute the Born-rule probability vector p_i = Tr(P_i rho).

    Parameters
    ----------
    rho : numpy.ndarray
        Density matrix.
    projectors : list of numpy.ndarray
        Computational basis projectors.

    """
    probs = np.array([np.trace(P @ rho).real for P in projectors])
    probs = probs / np.sum(probs)   # normalize (numerical safety)
    return probs


Sample from probability vector

(cumulative sum + random number, as written)

In [ ]:
import numpy as np

def sample_probability(probs):
    """
    Sample an index from a probability vector using cumulative sums.
    """
    r = np.random.rand()
    cumulative = 0.0

    for i, p in enumerate(probs):
        cumulative += p
        if r < cumulative:
            return i

    return len(probs) - 1  # fallback (numerical)


Define measurement(ρ)

In [ ]:
import numpy as np

def measurement(state):
    """
    Perform a computational-basis measurement.

    Parameters
    ----------
    state : numpy.ndarray
        State vector or density matrix.

    """
    
    if state.ndim == 1:
        rho = np.outer(state, state.conj())
    elif state.ndim == 2:
        rho = state
    else:
        raise ValueError("State must be vector or density matrix")

    dim = rho.shape[0]
   P = projectors(dim)
    probs = born_rule(rho, P)

    outcome = sample_probability(probs)
    return outcome

    psi = np.array([1/np.sqrt(2), 1/np.sqrt(2)])
print(measurement(psi))