In [1]:
%pip install -e .


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Obtaining file:///home/772a0560-9cb7-4270-b879-16761470b567/quantum_gate_package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for quantum-gate-package (pyproject.toml) ... done
  Created wheel for quantum-gate-package: filename=quantum_gate_package-0.1.0-0.editable-py3-none-any.whl size=2665 sha256=16d81349904b32e7c0d5f673d8da7bd069f872a83769367002b89ca42ee59fbe
  Stored in directory: /tmp/pip-ephem-wheel-cache-v7y808uz/wheels/54/d6/5f/f62616e79a744ee2b48e1e8952df3b17802a399c391d96e721
Successfully built quantum-gate-package
  Attempting uninstall: quantum-gate-package
    Found existing installation: quantum-gate-package 0.1.0
    Uninstalling quantum-gate-package-0.1.0:
      Successfully


This program builds a GENERAL CONTROLLED quantum gate (Controlled-U)
for an N-qubit quantum register using NumPy.

• Works for ANY number of qubits (N)
• Control and target qubits can be at ANY position
• Works on ANY quantum state (superposition / entangled)

In [2]:
from quantum_gate_package import I, X, Y,Z,H,P0,P1

In [22]:
import numpy as np


"""
    Build a general controlled-U gate on N qubits.
    U       : 2x2 unitary (target gate)
    control : index of control qubit (0 = first qubit)
    target  : index of target qubit
    N       : total number of qubits
    """

def kron_all(ops):
    """Kronecker product of a list of operators."""
    result = ops[0]
    for op in ops[1:]:
        result = np.kron(result, op)
    return result
    

def controlled_gate(U, control, target, N):
    """
    Build a general Controlled-U gate on N qubits.
    PARAMETERS
    ----------
    U : 2x2 numpy array
        Single-qubit unitary gate applied to the target qubit
    control : int
        Index of the CONTROL qubit (0 = first qubit)
    target : int
        Index of the target qubit

    N : int
        Total number of qubits in the system
    """

    # ops_0 → operators when control qubit = |0⟩
    # ops_1 → operators when control qubit = |1⟩

    ops_0 = []
    ops_1 = []

    for i in range(N):

        # If this qubit is the CONTROL qubit
        if i == control:
            ops_0.append(P0)   # control = |0⟩
            ops_1.append(P1)   # control = |1⟩

        # If this qubit is the TARGET qubit
        elif i == target:
            ops_0.append(I)    # do nothing when control = |0⟩
            ops_1.append(U)    # apply U when control = |1⟩

        # All other qubits remain unchanged
        else:
            ops_0.append(I)
            ops_1.append(I)

    CU = kron_all(ops_0) + kron_all(ops_1)

    return CU

#Example

N = 3 
psi = np.zeros(2**N)
psi[0] = 1
# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)

print(CNOT2_0)
psi_out = CNOT2_0 @ psi
print(psi_out) 

#Example: CNOT (last = control, first = target)

X = np.array([[0, 1], [1, 0]])

N = 3
control = 0   # last qubit
target = 1   # first qubit

CNOT0_1 = controlled_gate(X, control, target, N)
print(CNOT0_1)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
[1. 0. 0. 0. 0. 0. 0. 0.]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]


In [21]:
import numpy as np

def controlled_gate(U, control, target, N):
    """
    Build a general controlled-U gate on N qubits.
    
    U       : 2x2 unitary (target gate)
    control : index of control qubit (0 = first qubit)
    target  : index of target qubit
    N       : total number of qubits
    """
    ops_0 = []
    ops_1 = []

    for i in range(N):
        if i == control:
            ops_0.append(P0)
            ops_1.append(P1)
        elif i == target:
            ops_0.append(I)
            ops_1.append(U)
        else:
            ops_0.append(I)
            ops_1.append(I)

    def kron_all(ops):
        result = ops[0]
        for op in ops[1:]:
            result = np.kron(result, op)
        return result
    return kron_all(ops_0) + kron_all(ops_1)

    #Example: CNOT (last = control, first = target)

X = np.array([[0, 1], [1, 0]])

N = 3
control = 0   # last qubit
target = 1   # first qubit

CNOT = controlled_gate(X, control, target, N)
print(CNOT)


[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
