In [1]:
%pip install -e .


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Obtaining file:///home/772a0560-9cb7-4270-b879-16761470b567/quantum_gate_package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for quantum-gate-package (pyproject.toml) ... done
  Created wheel for quantum-gate-package: filename=quantum_gate_package-0.1.0-0.editable-py3-none-any.whl size=2665 sha256=2e3064d956b8a9ad027d866519a2a7a5c07a635574818e06c1e5a6512b71978a
  Stored in directory: /tmp/pip-ephem-wheel-cache-9tlg1u4c/wheels/54/d6/5f/f62616e79a744ee2b48e1e8952df3b17802a399c391d96e721
Successfully built quantum-gate-package
  Attempting uninstall: quantum-gate-package
    Found existing installation: quantum-gate-package 0.1.0
    Uninstalling quantum-gate-package-0.1.0:
      Successfully

In [2]:
from quantum_gate_package import I, X, Y, Z, H, P0, P1, controlled_gate, projectors,U_two_gates

This program builds a general control gate (Controlled-U) for an N-qubit quantum register

• Works for any number of qubits (N) • Control and target qubits can be at any position • Works on any quantum state (superposition / entangled)

In [3]:
import numpy as np

#Example 1
N = 2 

# Control = last qubit, Target = first qubit
control = 0
target = 1
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 2-qubit CNOT (control=1, target=0)
N = 2
control = 1
target = 0

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [11]:
import numpy as np

#Example 1
N = 3 

# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 3-qubit CNOT (control=2, target=0)
N = 3
control = 1
target = 1

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

# Example 3: 2-qubit CNOT (control=2, target=0)
N =2
control =1
target = 0

CNOT= controlled_gate(X, control, target, N)
print(CNOT)

N = 4
control = 0
target = 3

C_X = controlled_gate(I, control, target, N)
print(C_X)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]


ValueError: Control and target must be different.

In [6]:
import numpy as np

#Example
N = 3
i = 2
j = 2

U_full = U_two_gates(X, X, i, j, N)

initial_state = np.zeros(2**N)
initial_state[7] = 1

state_after_U = U_full @ initial_state
print(state_after_U)

[0. 0. 0. 0. 0. 0. 0. 1.]


Create a function that generates a complete set of projectors
(computational basis)

{𝑃𝑖}, 𝑃𝑖=∣𝑖⟩⟨𝑖∣

In [10]:
import numpy as np

    #Example_1
P = projectors(2)
print(P[0])
print(P[1])

 #Example_2
P = projectors(4)
print(P[0])
print(P[3])
print(P[1])
print(P[2])

 #Example_3
P = projectors(8)
print(P[0])
print(P[7])

[[1. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
