In [1]:
%pip install -e .


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Obtaining file:///home/772a0560-9cb7-4270-b879-16761470b567/quantum_gate_package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for quantum-gate-package (pyproject.toml) ... done
  Created wheel for quantum-gate-package: filename=quantum_gate_package-0.1.0-0.editable-py3-none-any.whl size=2665 sha256=35226d0df158b35ee83e7dbfefa2f312cd7fa6e445d1e2911cade626e0ffb22b
  Stored in directory: /tmp/pip-ephem-wheel-cache-uwosmqge/wheels/2f/05/c8/eb879c95f0dee4bf1653487281366d62e91084078e3a2ab57e
Successfully built quantum-gate-package
  Attempting uninstall: quantum-gate-package
    Found existing installation: quantum-gate-package 0.1.0
    Uninstalling quantum-gate-package-0.1.0:
      Successfully

In [2]:
from quantum_gate_package import I, X,P0, P1, H, Z,Y,S,T,rotation_gate,CNOT,controlled_gate

In [3]:
import numpy as np

X = P0 + P1
print(X)

[[1 0]
 [0 1]]


In [4]:
import numpy as np

CZ=np.kron(P0,I) + np.kron(P1,Z)
print(CZ)

[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]


In [5]:
import numpy as np

S01 = P0 @ X @ P1   
S10 = P1 @ X @ P0   
SWAP = (np.kron(P0, P0) +
        np.kron(P1, P1) +
        np.kron(S01, S10) +
        np.kron(S10, S01))

print(SWAP)

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [6]:
import numpy as np

CCX=np.kron(P0,np.kron(I,I))+np.kron(P1,np.kron(P0,I))+np.kron(P1,np.kron(P1,X))
print(CCX)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [7]:
import numpy as np 


initial_state = np.array([1,0,0,0,
                          0,0,0,0])
H_q0 = np.kron(H, np.kron(I, I))
state_after_H =  H_q0@ initial_state

CNOT_q0_q2 = np.kron(P0, np.kron(I, I)) + np.kron(P1, np.kron(I, X))
state_after_CNOT_q0_q2 = CNOT_q0_q2 @ state_after_H

CNOT_q0_q1 = np.kron(P0, np.kron(I, I)) + np.kron(P1, np.kron(X, I))
state_after_q0_q1 = CNOT_q0_q1 @ state_after_CNOT_q0_q2


CNOT_q1_q0 = np.kron(np.kron(I, P0), I) + np.kron(np.kron(I, P1),X )
state_after_CNOT_q1_q0 = CNOT_q1_q0 @ state_after_q0_q1

print(state_after_CNOT_q1_q0)

[0.70710678 0.         0.         0.         0.70710678 0.
 0.         0.        ]


In [8]:
import numpy as np 

initial_state = np.array([0,0,0,0,
                          0,0,0,1])

H_q0 = np.kron(H, np.kron(I, I))
state_after_H =  H_q0@ initial_state

CNOT_q0_q2 = np.kron(P0, np.kron(I, I)) + np.kron(P1, np.kron(I, X))
state_after_CNOT_q0_q2 = CNOT_q0_q2 @ state_after_H

CNOT_q0_q1 = np.kron(P0, np.kron(I, I)) + np.kron(P1, np.kron(X, I))
state_after_q0_q1 = CNOT_q0_q1 @ state_after_CNOT_q0_q2


CNOT_q1_q0 = np.kron(I, np.kron(P0,I)) + np.kron(np.kron(I, P1), X)
state_after_CNOT_q1_q0 = CNOT_q1_q0 @ state_after_q0_q1

print(state_after_CNOT_q1_q0)

[ 0.          0.          0.          0.70710678  0.          0.
  0.         -0.70710678]


This program builds a general control gate (Controlled-U) for an N-qubit quantum register

• Works for any number of qubits (N) • Control and target qubits can be at any position • Works on any quantum state (superposition / entangled)

In [9]:
import numpy as np

#Example 1
N = 3 

# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 3-qubit CNOT (control=2, target=0)
N = 3
control = 0
target = 1

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

# Example 3: 2-qubit CNOT (control=2, target=0)
N = 2
control =1
target = 0

CNOT= controlled_gate(X, control, target, N)
print(CNOT)

N = 4
control = 0
target = 3

C_X = controlled_gate(I, control, target, N)
print(C_X)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [10]:
import numpy as np

#Example 1
N = 3 

# Control = last qubit, Target = first qubit
control = 2
target = 0
CNOT2_0 = controlled_gate(X, control, target, N)
print(CNOT2_0)

# Example 2: 3-qubit CNOT (control=2, target=0)
N = 3
control = 0
target = 1

CNOT_2_0 = controlled_gate(X, control, target, N)
print(CNOT_2_0)

# Example 3: 2-qubit CNOT (control=2, target=0)
N = 2
control =1
target = 0

CNOT= controlled_gate(X, control, target, N)
print(CNOT)

N = 4
control = 0
target = 3

C_X = controlled_gate(I, control, target, N)
print(C_X)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
